const PROJECTS = [
  { tag: "Airport / Infrastructure", title: "Hazrat Shahjalal International Airport — Terminal 03", body: "Quality control and technical coordination experience on fire-rated steel doors, roller shutters and fire-rated windows within the Terminal 03 expansion project.", image: "/images/project-kestrel.png" },
  { tag: "Commercial", title: "Commercial Building & Fit-out Works", body: "Construction, fit-out and finishing solutions coordinated around quality, safety, programme and client requirements.", image: "/images/project-birchwood.png" },
  { tag: "Infrastructure", title: "RCC Pavement & Site Development", body: "Engineering and construction support for site development, RCC pavement, earthwork and associated infrastructure works.", image: "/images/project-marlowe.png" },
  { tag: "Engineering Consultancy", title: "QA/QC & Technical Documentation", body: "Professional inspection, material documentation, WIR/MIR/MAR records, BOQ support and quality-control coordination throughout project delivery.", image: "/images/project-nordhaven.png" },
]

export function Projects() {
  return <section id="projects" className="bg-[#f5f1e8] px-6 py-7 md:px-12 md:py-8"><h2 className="border-b border-black/20 pb-5 text-[38px] leading-none tracking-[-.045em] md:text-[40px]">Selected Project Experience</h2><div className="pt-8">{PROJECTS.map((project) => <article key={project.title} className="grid gap-8 border-b border-black/20 py-8 first:pt-0 md:grid-cols-[190px_492px_1fr] md:items-start"><div className="text-[11px] font-semibold">Project Experience</div><div className="overflow-hidden rounded-[3px]"><img src={project.image} alt={project.title} className="h-[327px] w-full object-cover transition-transform duration-700 hover:scale-[1.025]" /></div><div><span className="inline-block rounded-[3px] border border-black/50 px-2 py-1 text-[10px]">{project.tag}</span><h3 className="mt-5 text-[16px] font-medium tracking-[-.02em]">{project.title}</h3><p className="mt-2 max-w-[400px] text-[14px] leading-[1.25] text-black/70">{project.body}</p></div></article>)}</div></section>
}
